language: haskell

before_install:
  # Instructions taken from https://github.com/commercialhaskell/stack/wiki/Downloads
  - wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
  - echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
  - sudo apt-get update
  - sudo apt-get install stack -y

install:
  - stack setup
  - stack --resolver ghc-7.10 setup --reinstall

script:
  - stack test
  - STACK_YAML=stack-7.10.yaml stack install happy && (sleep 60; echo 1) && STACK_YAML=stack-7.10.yaml stack install ide-backend-server && (sleep 60; echo 1) && STACK_YAML=stack-7.10.yaml stack test